# Generated by Django 4.1.2 on 2022-10-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dijeta_je_meta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staruserweightandheight',
            name='current_weight',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='staruserweightandheight',
            name='height',
            field=models.IntegerField(),
        ),
    ]
