# Generated by Django 4.1.2 on 2022-10-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dijeta_je_meta', '0002_alter_staruserweightandheight_current_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staruserweightandheight',
            name='name',
            field=models.CharField(default='', max_length=25),
        ),
    ]
