# Generated by Django 4.1.2 on 2022-10-19 09:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dijeta_je_meta', '0003_staruserweightandheight_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staruserweightandheight',
            old_name='name',
            new_name='ime',
        ),
        migrations.RemoveField(
            model_name='staruserweightandheight',
            name='current_weight',
        ),
        migrations.RemoveField(
            model_name='staruserweightandheight',
            name='diet_pace',
        ),
        migrations.RemoveField(
            model_name='staruserweightandheight',
            name='height',
        ),
        migrations.AddField(
            model_name='staruserweightandheight',
            name='stepen_gubitka_tezine',
            field=models.CharField(choices=[('Umeren', 'Umeren'), ('Agresivan', 'Agresivan')], default='Umeren', max_length=20),
        ),
        migrations.AddField(
            model_name='staruserweightandheight',
            name='trenutna_tezina',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='staruserweightandheight',
            name='visina',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
