# Generated by Django 4.1.2 on 2022-10-19 12:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dijeta_je_meta', '0004_rename_name_staruserweightandheight_ime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartUserWeightAndHeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(default='', max_length=25)),
                ('trenutna_tezina', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(400), django.core.validators.MinValueValidator(60)])),
                ('visina', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(250), django.core.validators.MinValueValidator(140)])),
                ('stepen_gubitka_tezine', models.CharField(choices=[('Umeren', 'Umeren'), ('Agresivan', 'Agresivan')], default='Umeren', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='StarUserWeightAndHeight',
        ),
    ]
