# Generated by Django 4.1.2 on 2022-10-20 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dijeta_je_meta', '0009_alter_newweight_current_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newweight',
            name='current_user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dijeta_je_meta.startuserweightandheight'),
        ),
    ]
