# Generated by Django 4.1.2 on 2022-10-20 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dijeta_je_meta', '0012_delete_newweight'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('nova_tezina', models.IntegerField(default=0)),
                ('current_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dijeta_je_meta.startuserweightandheight')),
            ],
        ),
    ]
