# Generated by Django 4.1.2 on 2022-10-20 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dijeta_je_meta', '0014_remove_newweight_current_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewWeight',
        ),
    ]
