# Generated by Django 4.1.2 on 2022-10-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dijeta_je_meta', '0021_remove_startuserweightandheight_polovi'),
    ]

    operations = [
        migrations.AddField(
            model_name='startuserweightandheight',
            name='polovi',
            field=models.CharField(choices=[('Muški', 'Muški'), ('Ženski', 'Ženski')], default='Muški', max_length=6),
        ),
    ]
