# Generated by Django 4.1.2 on 2022-10-21 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dijeta_je_meta', '0022_startuserweightandheight_polovi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='startuserweightandheight',
            old_name='polovi',
            new_name='pol',
        ),
    ]
