# Generated by Django 4.1.2 on 2022-10-25 10:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dijeta_je_meta', '0024_currentweight_delete_test'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currentweight',
            options={'ordering': ['-date_added']},
        ),
        migrations.AlterField(
            model_name='currentweight',
            name='trenutna_tezina',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(400), django.core.validators.MinValueValidator(45)]),
        ),
        migrations.AlterField(
            model_name='startuserweightandheight',
            name='pocetna_tezina',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(400), django.core.validators.MinValueValidator(45)]),
        ),
    ]
